Update for pypi
weka-io/rpyc pull request #3
Opened 2019-08-29 13:00 UTC by YuvalEvron

2019-08-29 13:18 UTC, YuvalEvron commented
@DoronCohen  - Can you please look at the log rotation area?

2019-09-01 08:43 UTC, doron-cohen requested changes
where is the log rotation changes?

2019-09-01 08:43 UTC, DoronCohen commented on .vscode/launch.json
> +{
pretty sure all files under `.vscode` should be ignored

2019-09-01 08:50 UTC, YuvalEvron commented
> @DoronCohen - Can you please look at the log rotation area?

lib/__init__ line 51

2019-09-01 08:51 UTC, YuvalEvron commented
> where is the log rotation changes?

lib/__init__ line 51

2019-10-03 13:03 UTC, closed without merging